### ISSUE TITLE
[FEAT]: CSS Snippet manager

### ISSUE THREAD

**Issue by 4Source** [4Source/vare-obsidian-plugin#17]
### Description of the unfavorable solution

CSS Snippets have no easy Manager as for Plugins or Themes.

### Describe the feature you would like to have

Repo like obsidian has with registered CSS Snippets with unique id.
CSS Snippets Repos could than be registered and have releases with just the ``<snippet-id>.css`` file
For recognizing the versions of current CSS Snippets a Comment header is needed with plugin id and version e.g.
``` CSS
/* 
id: "sticky-tree"
version: "0.1.0"
*/

div {

}

```
